/* Generated by DBCC, see <https://github.com/howerj/dbcc>

This file was generated by dbcc: See <https://github.com/howerj/dbcc>

For the professional version of this utility visit https://subleq.co.uk
The professional version includes support for CAN-FD, more languages, and
better MISRA-C support.


*/

#include "CHARGER_CAN.h"
#include <inttypes.h>

#define UNUSED(X) ((void)(X))

static inline uint64_t reverse_byte_order(uint64_t x) {
	x = (x & 0x00000000FFFFFFFF) << 32 | (x & 0xFFFFFFFF00000000) >> 32;
	x = (x & 0x0000FFFF0000FFFF) << 16 | (x & 0xFFFF0000FFFF0000) >> 16;
	x = (x & 0x00FF00FF00FF00FF) << 8  | (x & 0xFF00FF00FF00FF00) >> 8;
	return x;
}

static int pack_can_0x1806e5f4_BMS_Charger_Control(can_obj_charger_h_t *o, uint64_t *data) {
	register uint64_t x;
	register uint64_t m = 0;
	/* Charger_Max_Voltage: start-bit 7, length 16, endianess motorola, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x1806e5f4_BMS_Charger_Control.Charger_Max_Voltage)) & 0xffff;
	x <<= 48; 
	m |= x;
	/* Charger_Max_Current: start-bit 23, length 16, endianess motorola, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x1806e5f4_BMS_Charger_Control.Charger_Max_Current)) & 0xffff;
	x <<= 32; 
	m |= x;
	/* Charger_Control: start-bit 39, length 8, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x1806e5f4_BMS_Charger_Control.Charger_Control)) & 0xff;
	x <<= 24; 
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x1806e5f4_BMS_Charger_Control_tx = 1;
	return 5;
}

static int unpack_can_0x1806e5f4_BMS_Charger_Control(can_obj_charger_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 5)
		return -1;
	/* Charger_Max_Voltage: start-bit 7, length 16, endianess motorola, scaling 1, offset 0 */
	x = (m >> 48) & 0xffff;
	o->can_0x1806e5f4_BMS_Charger_Control.Charger_Max_Voltage = x;
	/* Charger_Max_Current: start-bit 23, length 16, endianess motorola, scaling 1, offset 0 */
	x = (m >> 32) & 0xffff;
	o->can_0x1806e5f4_BMS_Charger_Control.Charger_Max_Current = x;
	/* Charger_Control: start-bit 39, length 8, endianess motorola, scaling 1, offset 0 */
	x = (m >> 24) & 0xff;
	o->can_0x1806e5f4_BMS_Charger_Control.Charger_Control = x;
	o->can_0x1806e5f4_BMS_Charger_Control_rx = 1;
	o->can_0x1806e5f4_BMS_Charger_Control_time_stamp_rx = time_stamp;
	return 5;
}

int decode_can_0x1806e5f4_Charger_Max_Voltage(const can_obj_charger_h_t *o, int16_t *out) {
	int16_t rval = (int16_t)(o->can_0x1806e5f4_BMS_Charger_Control.Charger_Max_Voltage);
	*out = rval;
	return 0;
}

int encode_can_0x1806e5f4_Charger_Max_Voltage(can_obj_charger_h_t *o, int16_t in) {
	o->can_0x1806e5f4_BMS_Charger_Control.Charger_Max_Voltage = in;
	return 0;
}

int decode_can_0x1806e5f4_Charger_Max_Current(const can_obj_charger_h_t *o, int16_t *out) {
	int16_t rval = (int16_t)(o->can_0x1806e5f4_BMS_Charger_Control.Charger_Max_Current);
	*out = rval;
	return 0;
}

int encode_can_0x1806e5f4_Charger_Max_Current(can_obj_charger_h_t *o, int16_t in) {
	o->can_0x1806e5f4_BMS_Charger_Control.Charger_Max_Current = in;
	return 0;
}

int decode_can_0x1806e5f4_Charger_Control(const can_obj_charger_h_t *o, uint8_t *out) {
	uint8_t rval = (uint8_t)(o->can_0x1806e5f4_BMS_Charger_Control.Charger_Control);
	*out = rval;
	return 0;
}

int encode_can_0x1806e5f4_Charger_Control(can_obj_charger_h_t *o, uint8_t in) {
	o->can_0x1806e5f4_BMS_Charger_Control.Charger_Control = in;
	return 0;
}

int unpack_message_charger(can_obj_charger_h_t *o, const unsigned long id, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	switch (id) {
	case 0x1806e5f4: return unpack_can_0x1806e5f4_BMS_Charger_Control(o, data, dlc, time_stamp);
	default: break; 
	}
	return -1; 
}

int pack_message_charger(can_obj_charger_h_t *o, const unsigned long id, uint64_t *data) {
	switch (id) {
	case 0x1806e5f4: return pack_can_0x1806e5f4_BMS_Charger_Control(o, data);
	default: break; 
	}
	return -1; 
}

int message_dlc_charger(const unsigned long id) {
	switch (id) {
	case 0x1806e5f4: return 5;
	default: break; 
	}
	return -1; 
}

