/* CAN message encoder/decoder: automatically generated - do not edit.

  * @note  Generated on Sun Dec  7 23:27:59 2025
This file was generated by dbcc: See <https://github.com/howerj/dbcc>

For the professional version of this utility visit https://subleq.co.uk
The professional version includes support for CAN-FD, more languages, and
better MISRA-C support.


*/

#ifndef CHARGER_H
#define CHARGER_H

/* If the contents of this file have caused breaking changes for you, you could try using
   an older version of the generator. You can specify this on the command line with
   the -n option. */
#define DBCC_GENERATOR_VERSION (3)

#include <stdint.h>


#ifdef __cplusplus
extern "C" { 
#endif

#ifndef PREPACK
#define PREPACK
#endif

#ifndef POSTPACK
#define POSTPACK
#endif

#ifndef DBCC_DOUBLE_TYPE
#define DBCC_DOUBLE_TYPE
typedef double dbcc_double_t;
#endif

#ifndef DBCC_FLOAT_TYPE
#define DBCC_FLOAT_TYPE
typedef float dbcc_float_t;
#endif

#ifndef DBCC_TIME_STAMP
#define DBCC_TIME_STAMP
typedef uint32_t dbcc_time_stamp_t; /* Time stamp for message; you decide on units */
#endif

#ifndef DBCC_STATUS_ENUM
#define DBCC_STATUS_ENUM
typedef enum {
	DBCC_SIG_STAT_UNINITIALIZED_E = 0, /* Message never sent/received */
	DBCC_SIG_STAT_OK_E            = 1, /* Message ok */
	DBCC_SIG_STAT_ERROR_E         = 2, /* Encode/Decode/Timestamp/Any error */
} dbcc_signal_status_e;
#endif

#define CAN_ID_BMS_CHARGER_CONTROL (403105268) /* 0x1806e5f4 */

typedef PREPACK struct {
	int16_t Charger_Max_Voltage; /* scaling 1.0, offset 0.0, units none */
	int16_t Charger_Max_Current; /* scaling 1.0, offset 0.0, units none */
	uint8_t Charger_Control; /* scaling 1.0, offset 0.0, units none */
} POSTPACK can_0x1806e5f4_BMS_Charger_Control_t;

typedef PREPACK struct {
	dbcc_time_stamp_t can_0x1806e5f4_BMS_Charger_Control_time_stamp_rx;
	unsigned can_0x1806e5f4_BMS_Charger_Control_status : 2;
	unsigned can_0x1806e5f4_BMS_Charger_Control_tx : 1;
	unsigned can_0x1806e5f4_BMS_Charger_Control_rx : 1;
	can_0x1806e5f4_BMS_Charger_Control_t can_0x1806e5f4_BMS_Charger_Control;
} POSTPACK can_obj_charger_h_t;

int unpack_message_charger(can_obj_charger_h_t *o, const unsigned long id, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp);
int pack_message_charger(can_obj_charger_h_t *o, const unsigned long id, uint64_t *data);
int message_dlc_charger(const unsigned long id);

int decode_can_0x1806e5f4_Charger_Max_Voltage(const can_obj_charger_h_t *o, int16_t *out);
int encode_can_0x1806e5f4_Charger_Max_Voltage(can_obj_charger_h_t *o, int16_t in);
int decode_can_0x1806e5f4_Charger_Max_Current(const can_obj_charger_h_t *o, int16_t *out);
int encode_can_0x1806e5f4_Charger_Max_Current(can_obj_charger_h_t *o, int16_t in);
int decode_can_0x1806e5f4_Charger_Control(const can_obj_charger_h_t *o, uint8_t *out);
int encode_can_0x1806e5f4_Charger_Control(can_obj_charger_h_t *o, uint8_t in);


#ifdef __cplusplus
} 
#endif

#endif
