/* CAN message encoder/decoder: automatically generated - do not edit.

  * @note  Generated on Sun Dec  7 23:27:59 2025
This file was generated by dbcc: See <https://github.com/howerj/dbcc>

For the professional version of this utility visit https://subleq.co.uk
The professional version includes support for CAN-FD, more languages, and
better MISRA-C support.


*/

#ifndef VEHICLE_H
#define VEHICLE_H

/* If the contents of this file have caused breaking changes for you, you could try using
   an older version of the generator. You can specify this on the command line with
   the -n option. */
#define DBCC_GENERATOR_VERSION (3)

#include <stdint.h>


#ifdef __cplusplus
extern "C" { 
#endif

#ifndef PREPACK
#define PREPACK
#endif

#ifndef POSTPACK
#define POSTPACK
#endif

#ifndef DBCC_DOUBLE_TYPE
#define DBCC_DOUBLE_TYPE
typedef double dbcc_double_t;
#endif

#ifndef DBCC_FLOAT_TYPE
#define DBCC_FLOAT_TYPE
typedef float dbcc_float_t;
#endif

#ifndef DBCC_TIME_STAMP
#define DBCC_TIME_STAMP
typedef uint32_t dbcc_time_stamp_t; /* Time stamp for message; you decide on units */
#endif

#ifndef DBCC_STATUS_ENUM
#define DBCC_STATUS_ENUM
typedef enum {
	DBCC_SIG_STAT_UNINITIALIZED_E = 0, /* Message never sent/received */
	DBCC_SIG_STAT_OK_E            = 1, /* Message ok */
	DBCC_SIG_STAT_ERROR_E         = 2, /* Encode/Decode/Timestamp/Any error */
} dbcc_signal_status_e;
#endif

#define CAN_ID_M160_TEMPERATURE_SET_1 (160) /* 0xa0 */
#define CAN_ID_M161_TEMPERATURE_SET_2 (161) /* 0xa1 */
#define CAN_ID_M162_TEMPERATURE_SET_3 (162) /* 0xa2 */
#define CAN_ID_M163_ANALOG_INPUT_VOLTAGES (163) /* 0xa3 */
#define CAN_ID_M164_DIGITAL_INPUT_STATUS (164) /* 0xa4 */
#define CAN_ID_M165_MOTOR_POSITION_INFO (165) /* 0xa5 */
#define CAN_ID_M166_CURRENT_INFO (166) /* 0xa6 */
#define CAN_ID_M167_VOLTAGE_INFO (167) /* 0xa7 */
#define CAN_ID_M168_FLUX_ID_IQ_INFO (168) /* 0xa8 */
#define CAN_ID_M169_INTERNAL_VOLTAGES (169) /* 0xa9 */
#define CAN_ID_M170_INTERNAL_STATES (170) /* 0xaa */
#define CAN_ID_M171_FAULT_CODES (171) /* 0xab */
#define CAN_ID_M172_TORQUE_AND_TIMER_INFO (172) /* 0xac */
#define CAN_ID_M173_MODULATION_AND_FLUX_INFO (173) /* 0xad */
#define CAN_ID_M174_FIRMWARE_INFO (174) /* 0xae */
#define CAN_ID_M175_DIAG_DATA (175) /* 0xaf */
#define CAN_ID_M176_FAST_INFO (176) /* 0xb0 */
#define CAN_ID_M192_COMMAND_MESSAGE (192) /* 0xc0 */
#define CAN_ID_M193_READ_WRITE_PARAM_COMMAND (193) /* 0xc1 */
#define CAN_ID_M194_READ_WRITE_PARAM_RESPONSE (194) /* 0xc2 */
#define CAN_ID_BMS_FAULT (195) /* 0xc3 */
#define CAN_ID_READYTODRIVE (448) /* 0x1c0 */
#define CAN_ID_M188_U2C_MESSAGE_RXD (469) /* 0x1d5 */
#define CAN_ID_M187_U2C_COMMAND_TXD (471) /* 0x1d7 */
#define CAN_ID_BRAKELIGHT (528) /* 0x210 */
#define CAN_ID_BRAKEPRESSURE (560) /* 0x230 */
#define CAN_ID_WHEELSPEED (576) /* 0x240 */
#define CAN_ID_STEERINGPOT (592) /* 0x250 */
#define CAN_ID_MBRTEMPSENS (608) /* 0x260 */
#define CAN_ID_ECU_FRONT_BRAKETEMP (640) /* 0x280 */
#define CAN_ID_ECU_REAR_BRAKE_TEMP (656) /* 0x290 */
#define CAN_ID_APPS (688) /* 0x2b0 */
#define CAN_ID_ECU_REAR_IMU_GYRO (768) /* 0x300 */
#define CAN_ID_ECU_REAR_IMU_ACCEL (784) /* 0x310 */
#define CAN_ID_BMS_VOLTAGE_DATA (1220) /* 0x4c4 */
#define CAN_ID_BMS_TEMPERATURE_DATA (1221) /* 0x4c5 */
#define CAN_ID_BMS_PACK_DATA (1222) /* 0x4c6 */
#define CAN_ID_CANHEARTBEATLED (1280) /* 0x500 */
#define CAN_ID_CAN_BUS_DATA (1300) /* 0x514 */
#define CAN_ID_ECU_FRONT_CAN_ERR_COUNTS (1301) /* 0x515 */
#define CAN_ID_ECU_REAR_CAN_ERR_COUNTS (1302) /* 0x516 */
#define CAN_ID_TCU_CAN_ERR_COUNTS (1303) /* 0x517 */
#define CAN_ID_LV_BMS (2032) /* 0x7f0 */
#define CAN_ID_LV_BMS_2 (2033) /* 0x7f1 */

typedef PREPACK struct {
	/* D1_Module_A: IGBT Module A Temperature */
	/* scaling 0.1, offset 0.0, units degC */
	int16_t D1_Module_A;
	/* D2_Module_B: IGBT Module B Temperature */
	/* scaling 0.1, offset 0.0, units degC */
	int16_t D2_Module_B;
	/* D3_Module_C: IGBT Module C Temperature */
	/* scaling 0.1, offset 0.0, units degC */
	int16_t D3_Module_C;
	/* D4_Gate_Driver_Board: Gate Driver Board Temperature */
	/* scaling 0.1, offset 0.0, units degC */
	int16_t D4_Gate_Driver_Board;
} POSTPACK can_0x0a0_M160_Temperature_Set_1_t;

typedef PREPACK struct {
	/* D1_Control_Board_Temperature: Control Board Temperature */
	/* scaling 0.1, offset 0.0, units degC */
	int16_t D1_Control_Board_Temperature;
	/* D2_RTD1_Temperature: RTD input 1 (PT1000) Temperature */
	/* scaling 0.1, offset 0.0, units degC */
	int16_t D2_RTD1_Temperature;
	/* D3_RTD2_Temperature: RTD input 2 (PT1000) Temperature */
	/* scaling 0.1, offset 0.0, units degC */
	int16_t D3_RTD2_Temperature;
	/* D4_RTD3_Temperature: RTD input 3 (PT1000) Temperature (Gen 2 only) */
	/* scaling 0.1, offset 0.0, units degC */
	int16_t D4_RTD3_Temperature;
} POSTPACK can_0x0a1_M161_Temperature_Set_2_t;

typedef PREPACK struct {
	/* D1_RTD4_Temperature: RTD 4 (PT1000) Temperature (Gen 2 only) */
	/* scaling 0.1, offset 0.0, units degC */
	int16_t D1_RTD4_Temperature;
	/* D2_RTD5_Temperature: RTD 5 (PT1000) Temperature (Gen 2 only) */
	/* scaling 0.1, offset 0.0, units degC */
	int16_t D2_RTD5_Temperature;
	/* D3_Motor_Temperature: Motor Temperature Sensor */
	/* scaling 0.1, offset 0.0, units degC */
	int16_t D3_Motor_Temperature;
	/* D4_Torque_Shudder: Shudder compensation value of torque */
	/* scaling 0.1, offset 0.0, units Nm */
	int16_t D4_Torque_Shudder;
} POSTPACK can_0x0a2_M162_Temperature_Set_3_t;

typedef PREPACK struct {
	/* D1_Analog_Input_1: Voltage on Analog Input #1 */
	/* scaling 0.0, offset 0.0, units V */
	uint16_t D1_Analog_Input_1;
	/* D2_Analog_Input_2: Voltage on Analog Input #2 */
	/* scaling 0.0, offset 0.0, units V */
	uint16_t D2_Analog_Input_2;
	/* D3_Analog_Input_3: Voltage on Analog Input #3 */
	/* scaling 0.0, offset 0.0, units V */
	uint16_t D3_Analog_Input_3;
	/* D4_Analog_Input_4: Voltage on Analog Input #4 */
	/* scaling 0.0, offset 0.0, units V */
	uint16_t D4_Analog_Input_4;
	/* D5_Analog_Input_5: Voltage on Analog Input #5 */
	/* scaling 0.0, offset 0.0, units V */
	uint16_t D5_Analog_Input_5;
	/* D6_Analog_Input_6: Voltage on Analog Input #6 */
	/* scaling 0.0, offset 0.0, units V */
	uint16_t D6_Analog_Input_6;
} POSTPACK can_0x0a3_M163_Analog_Input_Voltages_t;

typedef PREPACK struct {
	/* D1_Digital_Input_1: Status of Digital Input #1 */
	/* scaling 1.0, offset 0.0, units boolean */
	uint8_t D1_Digital_Input_1;
	/* D2_Digital_Input_2: Status of Digital Input #2 */
	/* scaling 1.0, offset 0.0, units boolean */
	uint8_t D2_Digital_Input_2;
	/* D3_Digital_Input_3: Status of Digital Input #3 */
	/* scaling 1.0, offset 0.0, units boolean */
	uint8_t D3_Digital_Input_3;
	/* D4_Digital_Input_4: Status of Digital Input #4 */
	/* scaling 1.0, offset 0.0, units boolean */
	uint8_t D4_Digital_Input_4;
	/* D5_Digital_Input_5: Status of Digital Input #5 */
	/* scaling 1.0, offset 0.0, units boolean */
	uint8_t D5_Digital_Input_5;
	/* D6_Digital_Input_6: Status of Digital Input #6 */
	/* scaling 1.0, offset 0.0, units boolean */
	uint8_t D6_Digital_Input_6;
	/* D7_Digital_Input_7: Status of Digital Input #7 */
	/* scaling 1.0, offset 0.0, units boolean */
	uint8_t D7_Digital_Input_7;
	/* D8_Digital_Input_8: Status of Digital Input #8 */
	/* scaling 1.0, offset 0.0, units boolean */
	uint8_t D8_Digital_Input_8;
} POSTPACK can_0x0a4_M164_Digital_Input_Status_t;

typedef PREPACK struct {
	/* D1_Motor_Angle_Electrical: The Electrical Angle of the motor as read by the encoder or resolver */
	/* scaling 0.1, offset 0.0, units deg */
	uint16_t D1_Motor_Angle_Electrical;
	/* D2_Motor_Speed: The measured speed of the motor */
	/* scaling 1.0, offset 0.0, units rpm */
	int16_t D2_Motor_Speed;
	/* D3_Electrical_Output_Frequency: The actual electrical frequency of the inverter */
	/* scaling 0.1, offset 0.0, units Hz */
	int16_t D3_Electrical_Output_Frequency;
	/* D4_Delta_Resolver_Filtered: Used in calibration of resolver angle adjustment. */
	/* scaling 0.1, offset 0.0, units deg */
	int16_t D4_Delta_Resolver_Filtered;
} POSTPACK can_0x0a5_M165_Motor_Position_Info_t;

typedef PREPACK struct {
	/* D1_Phase_A_Current: The measured value of Phase A current */
	/* scaling 0.1, offset 0.0, units A */
	int16_t D1_Phase_A_Current;
	/* D2_Phase_B_Current: The measured value of Phase B current */
	/* scaling 0.1, offset 0.0, units A */
	int16_t D2_Phase_B_Current;
	/* D3_Phase_C_Current: The measured value of Phase C current */
	/* scaling 0.1, offset 0.0, units A */
	int16_t D3_Phase_C_Current;
	/* D4_DC_Bus_Current: The Calculated DC Bus Current */
	/* scaling 0.1, offset 0.0, units A */
	int16_t D4_DC_Bus_Current;
} POSTPACK can_0x0a6_M166_Current_Info_t;

typedef PREPACK struct {
	/* D1_DC_Bus_Voltage: The actual measured value of the DC bus voltage */
	/* scaling 0.1, offset 0.0, units V */
	int16_t D1_DC_Bus_Voltage;
	/* D2_Output_Voltage: The calculated value of the output voltage, in peak line-neutral volts */
	/* scaling 0.1, offset 0.0, units V */
	int16_t D2_Output_Voltage;
	/* D3_VAB_Vd_Voltage: Measured value of the voltage betwen phase A and Phase B */
	/* scaling 0.1, offset 0.0, units V */
	int16_t D3_VAB_Vd_Voltage;
	/* D4_VBC_Vq_Voltage: Measured value of the voltage between Phase B and Phase C */
	/* scaling 0.1, offset 0.0, units V */
	int16_t D4_VBC_Vq_Voltage;
} POSTPACK can_0x0a7_M167_Voltage_Info_t;

typedef PREPACK struct {
	/* D1_Flux_Command: The commanded flux */
	/* scaling 0.0, offset 0.0, units Wb */
	int16_t D1_Flux_Command;
	/* D2_Flux_Feedback: The estimated flux */
	/* scaling 0.0, offset 0.0, units Wb */
	int16_t D2_Flux_Feedback;
	/* D3_Id: The measured Id current */
	/* scaling 0.1, offset 0.0, units A */
	int16_t D3_Id;
	/* D4_Iq: The measured Iq current */
	/* scaling 0.1, offset 0.0, units A */
	int16_t D4_Iq;
} POSTPACK can_0x0a8_M168_Flux_ID_IQ_Info_t;

typedef PREPACK struct {
	/* D1_Reference_Voltage_1_5: Internal reference voltage */
	/* scaling 0.0, offset 0.0, units V */
	int16_t D1_Reference_Voltage_1_5;
	/* D2_Reference_Voltage_2_5: Internal reference voltage */
	/* scaling 0.0, offset 0.0, units V */
	int16_t D2_Reference_Voltage_2_5;
	/* D3_Reference_Voltage_5_0: Transducer voltage */
	/* scaling 0.0, offset 0.0, units V */
	int16_t D3_Reference_Voltage_5_0;
	/* D4_Reference_Voltage_12_0: 12V Input Voltage */
	/* scaling 0.0, offset 0.0, units V */
	int16_t D4_Reference_Voltage_12_0;
} POSTPACK can_0x0a9_M169_Internal_Voltages_t;

typedef PREPACK struct {
	/* D1_VSM_State: Different states for the vehicle state machine */
	/* scaling 1.0, offset 0.0, units none */
	uint8_t D1_VSM_State;
	/* D1_PWM_Frequency: The inverter PWM frequency */
	/* scaling 1.0, offset 0.0, units kHz */
	uint8_t D1_PWM_Frequency;
	/* D2_Inverter_State: Different states for the inverter state machine */
	/* scaling 1.0, offset 0.0, units none */
	uint8_t D2_Inverter_State;
	/* D5_Rolling_Counter: The current rolling counter value. */
	/* scaling 1.0, offset 0.0, units none */
	uint8_t D5_Rolling_Counter;
	/* D4_Inverter_Discharge_State: 0 = Disabled, 1 = Enabled, 2 = Speed Check, 3 = Active, 4 = Complete */
	/* scaling 1.0, offset 0.0, units none */
	uint8_t D4_Inverter_Discharge_State;
	/* D3_Relay_1_Status: 0=OFF, 1=ON */
	/* scaling 1.0, offset 0.0, units none */
	uint8_t D3_Relay_1_Status;
	/* D3_Relay_2_Status: 0=OFF, 1=ON */
	/* scaling 1.0, offset 0.0, units none */
	uint8_t D3_Relay_2_Status;
	/* D3_Relay_3_Status: 0=OFF, 1=ON */
	/* scaling 1.0, offset 0.0, units none */
	uint8_t D3_Relay_3_Status;
	/* D3_Relay_4_Status: 0=OFF, 1=ON */
	/* scaling 1.0, offset 0.0, units none */
	uint8_t D3_Relay_4_Status;
	/* D3_Relay_5_Status: 0=OFF, 1=ON */
	/* scaling 1.0, offset 0.0, units none */
	uint8_t D3_Relay_5_Status;
	/* D3_Relay_6_Status: 0=OFF, 1=ON */
	/* scaling 1.0, offset 0.0, units none */
	uint8_t D3_Relay_6_Status;
	/* D4_Inverter_Run_Mode: 0=Torque Mode, 1=Speed Mode */
	/* scaling 1.0, offset 0.0, units none */
	uint8_t D4_Inverter_Run_Mode;
	/* D5_Inverter_Command_Mode: 0=CAN mode, 1=VSM mode */
	/* scaling 1.0, offset 0.0, units none */
	uint8_t D5_Inverter_Command_Mode;
	/* D6_Inverter_Enable_State: 0=Inverter Disabled, 1=Inverter Enabled */
	/* scaling 1.0, offset 0.0, units none */
	uint8_t D6_Inverter_Enable_State;
	/* D6_Start_Mode_Active: If in Key Switch Mode 1 then indicates status of Start input being applied. 0 = not active, 1 = active */
	/* scaling 1.0, offset 0.0, units none */
	uint8_t D6_Start_Mode_Active;
	/* D6_Inverter_Enable_Lockout: 0=Lockout Disabled, 1=Lockout Enabled */
	/* scaling 1.0, offset 0.0, units none */
	uint8_t D6_Inverter_Enable_Lockout;
	/* D7_Direction_Command: 1 = Forward 0 = 'Reverse' if inverter enabled & 'Stopped' if inverter is disabled */
	/* scaling 1.0, offset 0.0, units none */
	uint8_t D7_Direction_Command;
	/* D7_BMS_Active: 0 = BMS Not Active, 1 = BMS Active */
	/* scaling 1.0, offset 0.0, units none */
	uint8_t D7_BMS_Active;
	/* D7_BMS_Torque_Limiting: 0 = Not Limiting, 1 = Limiting */
	/* scaling 1.0, offset 0.0, units none */
	uint8_t D7_BMS_Torque_Limiting;
	/* D7_Max_Speed_Limiting: 0 = Not Limiting, 1 = torque limiting due to maximum speed */
	/* scaling 1.0, offset 0.0, units none */
	uint8_t D7_Max_Speed_Limiting;
	/* D7_Low_Speed_Limiting: 0 = Not Limiting, 1 = Current limiting due to low motor speed */
	/* scaling 1.0, offset 0.0, units none */
	uint8_t D7_Low_Speed_Limiting;
} POSTPACK can_0x0aa_M170_Internal_States_t;

typedef PREPACK struct {
	/* D1_Post_Fault_Lo: Each bit represents a fault. Please refer to PM100 Users Manual for details. */
	/* scaling 1.0, offset 0.0, units none */
	uint16_t D1_Post_Fault_Lo;
	/* D2_Post_Fault_Hi: Each bit represents a fault. Please refer to PM100 Users Manual for details. */
	/* scaling 1.0, offset 0.0, units none */
	uint16_t D2_Post_Fault_Hi;
	/* D3_Run_Fault_Lo: Each bit represents a fault. Please refer to PM100 Users Manual for details. */
	/* scaling 1.0, offset 0.0, units none */
	uint16_t D3_Run_Fault_Lo;
	/* D4_Run_Fault_Hi: Each bit represents a fault. Please refer to PM100 Users Manual for details. */
	/* scaling 1.0, offset 0.0, units none */
	uint16_t D4_Run_Fault_Hi;
} POSTPACK can_0x0ab_M171_Fault_Codes_t;

typedef PREPACK struct {
	/* D3_Power_On_Timer: Updated every 3 msec. This will roll over in approximately 150 days! */
	/* scaling 0.0, offset 0.0, units sec */
	uint32_t D3_Power_On_Timer;
	/* D1_Commanded_Torque: The commanded Torque */
	/* scaling 0.1, offset 0.0, units Nm */
	int16_t D1_Commanded_Torque;
	/* D2_Torque_Feedback: Estimated motor torque feedback */
	/* scaling 0.1, offset 0.0, units Nm */
	int16_t D2_Torque_Feedback;
} POSTPACK can_0x0ac_M172_Torque_And_Timer_Info_t;

typedef PREPACK struct {
	/* D1_Modulation_Index: This is the modulation index. The scale factor is x100. To get the actual modulation index divide the value by 100. */
	/* scaling 0.0, offset 0.0, units none */
	int16_t D1_Modulation_Index;
	/* D2_Flux_Weakening_Output: This is the current output of the flux regulator. */
	/* scaling 0.1, offset 0.0, units A */
	int16_t D2_Flux_Weakening_Output;
	/* D3_Id_Command: The commanded D-axis current */
	/* scaling 0.1, offset 0.0, units A */
	int16_t D3_Id_Command;
	/* D4_Iq_Command: The commanded Q-axis current */
	/* scaling 0.1, offset 0.0, units A */
	int16_t D4_Iq_Command;
} POSTPACK can_0x0ad_M173_Modulation_And_Flux_Info_t;

typedef PREPACK struct {
	uint16_t D1_Project_Code_EEP_Ver; /* scaling 1.0, offset 0.0, units none */
	uint16_t D2_SW_Version; /* scaling 1.0, offset 0.0, units none */
	uint16_t D3_DateCode_MMDD; /* scaling 1.0, offset 0.0, units none */
	uint16_t D4_DateCode_YYYY; /* scaling 1.0, offset 0.0, units none */
} POSTPACK can_0x0ae_M174_Firmware_Info_t;

typedef PREPACK struct {
	int16_t D3_Diag_Data_1; /* scaling 1.0, offset 0.0, units none */
	int16_t D4_Diag_Data_2; /* scaling 1.0, offset 0.0, units none */
	int16_t D5_Diag_Data_3; /* scaling 1.0, offset 0.0, units none */
	uint8_t D1_Buffer_Record; /* scaling 1.0, offset 0.0, units none */
	uint8_t D2_Buffer_Segment; /* scaling 1.0, offset 0.0, units none */
} POSTPACK can_0x0af_M175_Diag_Data_t;

/* To enable fast message set CAN ACTIVE MSGS HI WORD to 0xFFFE. Setting to default value of 0xFFFF will disable the fast message. */
typedef PREPACK struct {
	/* Fast_Torque_Command: The commanded torque */
	/* scaling 0.1, offset 0.0, units Nm */
	int16_t Fast_Torque_Command;
	/* Fast_Torque_Feedback: The estimated torque */
	/* scaling 0.1, offset 0.0, units Nm */
	int16_t Fast_Torque_Feedback;
	/* Fast_Motor_Speed: Motor speed */
	/* scaling 1.0, offset 0.0, units rpm */
	int16_t Fast_Motor_Speed;
	/* Fast_DC_Bus_Voltage: DC Bus Voltage */
	/* scaling 0.1, offset 0.0, units V */
	int16_t Fast_DC_Bus_Voltage;
} POSTPACK can_0x0b0_M176_Fast_Info_t;

/* The command message is used to transmit data to the controller. This message is sent from a user supplied external controller to the PMxxx controller. */
typedef PREPACK struct {
	/* Torque_Command: Torque command when in torque mode */
	/* scaling 0.1, offset 0.0, units Nm */
	int16_t Torque_Command;
	/* Speed_Command: Speed commandused when in speed mode */
	/* scaling 1.0, offset 0.0, units rpm */
	int16_t Speed_Command;
	/* Torque_Limit_Command: Torque Limit, set to 0 to keep default */
	/* scaling 0.1, offset 0.0, units Nm */
	int16_t Torque_Limit_Command;
	/* RollingCounter: Rolling Counter command */
	/* scaling 1.0, offset 0.0, units Bits */
	uint8_t RollingCounter;
	/* Direction_Command: 0=CW, 1=CCW as veiwed from the shaft end of the motor */
	/* scaling 1.0, offset 0.0, units Bit */
	uint8_t Direction_Command;
	/* Inverter_Enable: 0=Inverter OFF, 1 = Inverter ON */
	/* scaling 1.0, offset 0.0, units Bit */
	uint8_t Inverter_Enable;
	/* Inverter_Discharge: 0=Discharge_Disable, 1=Discharge_Enable */
	/* scaling 1.0, offset 0.0, units Bit */
	uint8_t Inverter_Discharge;
	/* Speed_Mode_Enable: 0 = No change to mode, 1 = change to speed mode from torque mode */
	/* scaling 1.0, offset 0.0, units Bit */
	uint8_t Speed_Mode_Enable;
} POSTPACK can_0x0c0_M192_Command_Message_t;

/* Parameter Message sent as needed by VCU to request info, change EEPROM, or command a function. */
typedef PREPACK struct {
	/* D1_Parameter_Address_Command: Valid EEPROM Parameter CAN addresses are between 100 and 499. */
	/* scaling 1.0, offset 0.0, units none */
	uint16_t D1_Parameter_Address_Command;
	/* D3_Data_Command: All EEPROM data is 16 bits and is contained in bytes 4 and 5. */
	/* scaling 1.0, offset 0.0, units none */
	int16_t D3_Data_Command;
	/* D2_Read_Write_Command: 0=Read, 1=Write */
	/* scaling 1.0, offset 0.0, units none */
	uint8_t D2_Read_Write_Command;
} POSTPACK can_0x0c1_M193_Read_Write_Param_Command_t;

/* The inverter response to each Parameter message that is received. */
typedef PREPACK struct {
	/* D1_Parameter_Address_Response: Valid EEPROM Parameter CAN addresses are between 100 and 499. */
	/* scaling 1.0, offset 0.0, units none */
	uint16_t D1_Parameter_Address_Response;
	/* D3_Data_Response: All EEPROM data is 16 bits and is contained in bytes 4 and 5. Bytes 6 and 7 should be ignored. */
	/* scaling 1.0, offset 0.0, units none */
	int16_t D3_Data_Response;
	/* D2_Write_Success: 0=Write failure, 1=Success */
	/* scaling 1.0, offset 0.0, units none */
	uint8_t D2_Write_Success;
} POSTPACK can_0x0c2_M194_Read_Write_Param_Response_t;

/* HV BMS faults */
typedef PREPACK struct {
	uint8_t SEG1OV; /* scaling 1.0, offset 0.0, units none */
	uint8_t SEG1UV; /* scaling 1.0, offset 0.0, units none */
	uint8_t SEG1OT; /* scaling 1.0, offset 0.0, units none */
	uint8_t SEG1UT; /* scaling 1.0, offset 0.0, units none */
	uint8_t SEG2OV; /* scaling 1.0, offset 0.0, units none */
	uint8_t SEG2UV; /* scaling 1.0, offset 0.0, units none */
	uint8_t SEG2OT; /* scaling 1.0, offset 0.0, units none */
	uint8_t SEG2UT; /* scaling 1.0, offset 0.0, units none */
	uint8_t SEG3OV; /* scaling 1.0, offset 0.0, units none */
	uint8_t SEG3UV; /* scaling 1.0, offset 0.0, units none */
	uint8_t SEG3OT; /* scaling 1.0, offset 0.0, units none */
	uint8_t SEG3UT; /* scaling 1.0, offset 0.0, units none */
	uint8_t SEG4OV; /* scaling 1.0, offset 0.0, units none */
	uint8_t SEG4UV; /* scaling 1.0, offset 0.0, units none */
	uint8_t SEG4OT; /* scaling 1.0, offset 0.0, units none */
	uint8_t SEG4UT; /* scaling 1.0, offset 0.0, units none */
	uint8_t SEG5OV; /* scaling 1.0, offset 0.0, units none */
	uint8_t SEG5UV; /* scaling 1.0, offset 0.0, units none */
	uint8_t SEG5OT; /* scaling 1.0, offset 0.0, units none */
	uint8_t SEG5UT; /* scaling 1.0, offset 0.0, units none */
	uint8_t SEG6OV; /* scaling 1.0, offset 0.0, units none */
	uint8_t SEG6UV; /* scaling 1.0, offset 0.0, units none */
	uint8_t SEG6OT; /* scaling 1.0, offset 0.0, units none */
	uint8_t SEG6UT; /* scaling 1.0, offset 0.0, units none */
	uint8_t PACKOC; /* scaling 1.0, offset 0.0, units none */
	uint8_t IMD_Fault; /* scaling 1.0, offset 0.0, units none */
	uint8_t PEC_ERROR; /* scaling 1.0, offset 0.0, units none */
} POSTPACK can_0x0c3_BMS_Fault_t;

typedef PREPACK struct {
	uint8_t RTDActive; /* scaling 1.0, offset 0.0, units none */
	uint8_t Buzzer; /* scaling 1.0, offset 0.0, units none */
	uint8_t RegenStatus; /* scaling 1.0, offset 0.0, units none */
} POSTPACK can_0x1c0_ReadyToDrive_t;

typedef enum {
	CAN_0X1C0_READYTODRIVE_RTDACTIVE_DISABLE = 0,
	CAN_0X1C0_READYTODRIVE_RTDACTIVE_ENABLE = 1,
} can_0x1c0_ReadyToDrive_RTDActive_e;

typedef enum {
	CAN_0X1C0_READYTODRIVE_BUZZER_DISABLE = 0,
	CAN_0X1C0_READYTODRIVE_BUZZER_ENABLE = 1,
} can_0x1c0_ReadyToDrive_Buzzer_e;

typedef enum {
	CAN_0X1C0_READYTODRIVE_REGENSTATUS_DISABLE = 0,
	CAN_0X1C0_READYTODRIVE_REGENSTATUS_ENABLE = 1,
} can_0x1c0_ReadyToDrive_RegenStatus_e;

/* Response from Delphi DC/DC converter. */
typedef PREPACK struct {
	uint8_t D3_HV_Input_Current; /* scaling 1.0, offset 0.0, units none */
	uint8_t D6_14V_Monitor; /* scaling 1.0, offset 0.0, units none */
	uint8_t D8_14V_Current_Monitor; /* scaling 1.0, offset 0.0, units none */
	uint8_t D5_DTC_Index; /* scaling 1.0, offset 0.0, units none */
	uint8_t D4_DTC_Status; /* scaling 1.0, offset 0.0, units none */
	uint8_t D1_HV_Input_Current_Sensor_Validity; /* scaling 1.0, offset 0.0, units none */
	uint8_t D2_14V_Master_Fault; /* scaling 1.0, offset 0.0, units none */
	uint8_t D7_14V_Conditional; /* scaling 1.0, offset 0.0, units none */
} POSTPACK can_0x1d5_M188_U2C_Message_Rxd_t;

/* Enable message sent to Delphi DC/DC converter. */
typedef PREPACK struct {
	uint8_t D1_ID_Byte; /* scaling 1.0, offset 0.0, units none */
	uint8_t D2_Setpoint_Calc; /* scaling 1.0, offset 0.0, units none */
} POSTPACK can_0x1d7_M187_U2C_Command_Txd_t;

typedef PREPACK struct {
	uint8_t BrakeLightActive; /* scaling 1.0, offset 0.0, units none */
} POSTPACK can_0x210_BrakeLight_t;

typedef enum {
	CAN_0X210_BRAKELIGHT_BRAKELIGHTACTIVE_DISABLE = 0,
	CAN_0X210_BRAKELIGHT_BRAKELIGHTACTIVE_ENABLE = 1,
} can_0x210_BrakeLight_BrakeLightActive_e;

typedef PREPACK struct {
	int16_t BrakeSensor1; /* scaling 0.1, offset 0.0, units psi */
	int16_t BrakeSensor2; /* scaling 0.1, offset 0.0, units psi */
} POSTPACK can_0x230_BrakePressure_t;

typedef PREPACK struct {
	int16_t SpeedFrontRight; /* scaling 1.0, offset 0.0, units rpm */
	int16_t SpeedFrontLeft; /* scaling 1.0, offset 0.0, units rpm */
	int16_t SpeedRearRight; /* scaling 1.0, offset 0.0, units rpm */
	int16_t SpeedRearLeft; /* scaling 1.0, offset 0.0, units rpm */
} POSTPACK can_0x240_WheelSpeed_t;

typedef PREPACK struct {
	int16_t SteeringPotAngle; /* scaling 0.1, offset 0.0, units none */
} POSTPACK can_0x250_SteeringPot_t;

typedef PREPACK struct {
	int16_t Temperature; /* scaling 0.1, offset 0.0, units degC */
} POSTPACK can_0x260_MBRTempSens_t;

typedef PREPACK struct {
	uint16_t ECU_FRONT_BrakeTemp_FR; /* scaling 1.0, offset 0.0, units degC */
	uint16_t ECU_FRONT_BrakeTemp_FL; /* scaling 1.0, offset 0.0, units degC */
} POSTPACK can_0x280_ECU_FRONT_BrakeTemp_t;

typedef PREPACK struct {
	uint16_t ECU_REAR_Brake_Temp_RR; /* scaling 1.0, offset 0.0, units degC */
	uint16_t ECU_REAR_Brake_Temp_RL; /* scaling 1.0, offset 0.0, units degC */
} POSTPACK can_0x290_ECU_REAR_Brake_Temp_t;

typedef PREPACK struct {
	int16_t APPS1; /* scaling 0.0, offset 0.0, units percent */
	int16_t APPS2; /* scaling 0.0, offset 0.0, units percent */
} POSTPACK can_0x2b0_APPS_t;

typedef PREPACK struct {
	int16_t ECU_REAR_IMU_GYRO_RAW_X; /* scaling 0.1, offset 0.0, units deg/s */
	int16_t ECU_REAR_IMU_GYRO_RAW_Y; /* scaling 0.1, offset 0.0, units deg/s */
	int16_t ECU_REAR_IMU_GYRO_RAW_Z; /* scaling 0.1, offset 0.0, units deg/s */
} POSTPACK can_0x300_ECU_REAR_IMU_GYRO_t;

typedef PREPACK struct {
	int16_t ECU_REAR_IMU_ACCEL_RAW_X; /* scaling 0.0, offset 0.0, units g */
	int16_t ECU_REAR_IMU_ACCEL_RAW_Y; /* scaling 0.0, offset 0.0, units g */
	int16_t ECU_REAR_IMU_ACCEL_RAW_Z; /* scaling 0.0, offset 0.0, units g */
} POSTPACK can_0x310_ECU_REAR_IMU_ACCEL_t;

/* HV battery cell voltages data */
typedef PREPACK struct {
	int16_t Max_Voltage; /* scaling 0.0, offset 1.5, units V */
	int16_t Min_Voltage; /* scaling 0.0, offset 1.5, units V */
	int16_t Avg_Voltage; /* scaling 0.0, offset 1.5, units V */
	uint8_t Max_Voltage_Location; /* scaling 1.0, offset 0.0, units none */
	uint8_t Min_Voltage_Location; /* scaling 1.0, offset 0.0, units none */
} POSTPACK can_0x4c4_BMS_Voltage_Data_t;

/* HV battery temperature data */
typedef PREPACK struct {
	int16_t Max_Temperature; /* scaling 0.0, offset 0.0, units degC */
	int16_t Min_Temperature; /* scaling 0.0, offset 0.0, units degC */
	int16_t Avg_Temperature; /* scaling 0.0, offset 0.0, units degC */
	uint8_t Max_Temperature_Location; /* scaling 1.0, offset 0.0, units none */
	uint8_t Min_Temperature_Location; /* scaling 1.0, offset 0.0, units none */
} POSTPACK can_0x4c5_BMS_Temperature_Data_t;

/* HV battery pack data */
typedef PREPACK struct {
	uint16_t Pack_Voltage; /* scaling 0.0, offset 0.0, units V */
	int16_t Pack_Current; /* scaling 0.0, offset 0.0, units A */
} POSTPACK can_0x4c6_BMS_Pack_Data_t;

typedef PREPACK struct {
	uint8_t HeartBit; /* scaling 1.0, offset 0.0, units none */
} POSTPACK can_0x500_CANHeartBeatLED_t;

typedef enum {
	CAN_0X500_CANHEARTBEATLED_HEARTBIT_DISABLE = 0,
	CAN_0X500_CANHEARTBEATLED_HEARTBIT_ENABLE = 1,
} can_0x500_CANHeartBeatLED_HeartBit_e;

/* CAN bus statistics */
typedef PREPACK struct {
	uint16_t Bus_Load; /* scaling 0.0, offset 0.0, units percent */
} POSTPACK can_0x514_CAN_Bus_Data_t;

typedef PREPACK struct {
	uint16_t ECU_FRONT_TX_Hw_Err_Count; /* scaling 1.0, offset 0.0, units Errors */
	uint16_t ECU_FRONT_TX_Sw_Err_Count; /* scaling 1.0, offset 0.0, units Errors */
	uint16_t ECU_FRONT_RX_Hw_Err_Count; /* scaling 1.0, offset 0.0, units Errors */
	uint16_t ECU_FRONT_RX_Sw_Err_Count; /* scaling 1.0, offset 0.0, units Errors */
} POSTPACK can_0x515_ECU_FRONT_Can_Err_Counts_t;

typedef PREPACK struct {
	uint16_t ECU_REAR_TX_Hw_Err_Count; /* scaling 1.0, offset 0.0, units Errors */
	uint16_t ECU_REAR_TX_Sw_Err_Count; /* scaling 1.0, offset 0.0, units Errors */
	uint16_t ECU_REAR_RX_Hw_Err_Count; /* scaling 1.0, offset 0.0, units Errors */
	uint16_t ECU_REAR_RX_Sw_Err_Count; /* scaling 1.0, offset 0.0, units Errors */
} POSTPACK can_0x516_ECU_REAR_Can_Err_Counts_t;

typedef PREPACK struct {
	uint16_t TCU_TX_Hw_Err_Count; /* scaling 1.0, offset 0.0, units Errors */
	uint16_t TCU_TX_Sw_Err_Count; /* scaling 1.0, offset 0.0, units Errors */
	uint16_t TCU_RX_Hw_Err_Count; /* scaling 1.0, offset 0.0, units Errors */
	uint16_t TCU_RX_Sw_Err_Count; /* scaling 1.0, offset 0.0, units Errors */
} POSTPACK can_0x517_TCU_Can_Err_Counts_t;

/* Measurements for LV BMS */
typedef PREPACK struct {
	uint16_t LV_BMS_Voltage; /* scaling 1.0, offset 0.0, units mV */
	uint16_t LV_BMS_Current; /* scaling 1.0, offset 0.0, units mA */
	uint16_t LV_BMS_Temperature; /* scaling 1.0, offset 0.0, units degC */
	/* LV_BMS_Battery_Status: A_bunch_of_bit_masks,_BQ76905_TRM_pg_75 */
	/* scaling 1.0, offset 0.0, units none */
	uint16_t LV_BMS_Battery_Status;
} POSTPACK can_0x7f0_LV_BMS_t;

/* More Measurements for LV BMS */
typedef PREPACK struct {
	uint16_t LV_BMS_Min_Cell_Voltage; /* scaling 1.0, offset 0.0, units mV */
	uint16_t LV_BMS_Max_Cell_Voltage; /* scaling 1.0, offset 0.0, units mV */
	uint16_t LV_BMS_Avg_Cell_Voltage; /* scaling 1.0, offset 0.0, units mV */
	uint8_t LV_BMS_Balancing_Status_Bitmask; /* scaling 1.0, offset 0.0, units none */
	uint8_t LV_BMS_Fault_Reg_Out; /* scaling 1.0, offset 0.0, units none */
	uint8_t LV_BMS_Fault_Current_Protection_Latch; /* scaling 1.0, offset 0.0, units none */
	uint8_t LV_BMS_Fault_Overcurrent_Charge; /* scaling 1.0, offset 0.0, units none */
	uint8_t LV_BMS_Fault_Overcurrent_Discharge_2; /* scaling 1.0, offset 0.0, units none */
	uint8_t LV_BMS_Fault_Overcurrent_Discharge_1; /* scaling 1.0, offset 0.0, units none */
	uint8_t LV_BMS_Fault_Short_Circuit_Discharge; /* scaling 1.0, offset 0.0, units none */
	uint8_t LV_BMS_Fault_Cell_Undervoltage; /* scaling 1.0, offset 0.0, units none */
	uint8_t LV_BMS_Fault_Cell_Overvoltage; /* scaling 1.0, offset 0.0, units none */
} POSTPACK can_0x7f1_LV_BMS_2_t;

typedef PREPACK struct {
	dbcc_time_stamp_t can_0x0a0_M160_Temperature_Set_1_time_stamp_rx;
	dbcc_time_stamp_t can_0x0a1_M161_Temperature_Set_2_time_stamp_rx;
	dbcc_time_stamp_t can_0x0a2_M162_Temperature_Set_3_time_stamp_rx;
	dbcc_time_stamp_t can_0x0a3_M163_Analog_Input_Voltages_time_stamp_rx;
	dbcc_time_stamp_t can_0x0a4_M164_Digital_Input_Status_time_stamp_rx;
	dbcc_time_stamp_t can_0x0a5_M165_Motor_Position_Info_time_stamp_rx;
	dbcc_time_stamp_t can_0x0a6_M166_Current_Info_time_stamp_rx;
	dbcc_time_stamp_t can_0x0a7_M167_Voltage_Info_time_stamp_rx;
	dbcc_time_stamp_t can_0x0a8_M168_Flux_ID_IQ_Info_time_stamp_rx;
	dbcc_time_stamp_t can_0x0a9_M169_Internal_Voltages_time_stamp_rx;
	dbcc_time_stamp_t can_0x0aa_M170_Internal_States_time_stamp_rx;
	dbcc_time_stamp_t can_0x0ab_M171_Fault_Codes_time_stamp_rx;
	dbcc_time_stamp_t can_0x0ac_M172_Torque_And_Timer_Info_time_stamp_rx;
	dbcc_time_stamp_t can_0x0ad_M173_Modulation_And_Flux_Info_time_stamp_rx;
	dbcc_time_stamp_t can_0x0ae_M174_Firmware_Info_time_stamp_rx;
	dbcc_time_stamp_t can_0x0af_M175_Diag_Data_time_stamp_rx;
	dbcc_time_stamp_t can_0x0b0_M176_Fast_Info_time_stamp_rx;
	dbcc_time_stamp_t can_0x0c0_M192_Command_Message_time_stamp_rx;
	dbcc_time_stamp_t can_0x0c1_M193_Read_Write_Param_Command_time_stamp_rx;
	dbcc_time_stamp_t can_0x0c2_M194_Read_Write_Param_Response_time_stamp_rx;
	dbcc_time_stamp_t can_0x0c3_BMS_Fault_time_stamp_rx;
	dbcc_time_stamp_t can_0x1c0_ReadyToDrive_time_stamp_rx;
	dbcc_time_stamp_t can_0x1d5_M188_U2C_Message_Rxd_time_stamp_rx;
	dbcc_time_stamp_t can_0x1d7_M187_U2C_Command_Txd_time_stamp_rx;
	dbcc_time_stamp_t can_0x210_BrakeLight_time_stamp_rx;
	dbcc_time_stamp_t can_0x230_BrakePressure_time_stamp_rx;
	dbcc_time_stamp_t can_0x240_WheelSpeed_time_stamp_rx;
	dbcc_time_stamp_t can_0x250_SteeringPot_time_stamp_rx;
	dbcc_time_stamp_t can_0x260_MBRTempSens_time_stamp_rx;
	dbcc_time_stamp_t can_0x280_ECU_FRONT_BrakeTemp_time_stamp_rx;
	dbcc_time_stamp_t can_0x290_ECU_REAR_Brake_Temp_time_stamp_rx;
	dbcc_time_stamp_t can_0x2b0_APPS_time_stamp_rx;
	dbcc_time_stamp_t can_0x300_ECU_REAR_IMU_GYRO_time_stamp_rx;
	dbcc_time_stamp_t can_0x310_ECU_REAR_IMU_ACCEL_time_stamp_rx;
	dbcc_time_stamp_t can_0x4c4_BMS_Voltage_Data_time_stamp_rx;
	dbcc_time_stamp_t can_0x4c5_BMS_Temperature_Data_time_stamp_rx;
	dbcc_time_stamp_t can_0x4c6_BMS_Pack_Data_time_stamp_rx;
	dbcc_time_stamp_t can_0x500_CANHeartBeatLED_time_stamp_rx;
	dbcc_time_stamp_t can_0x514_CAN_Bus_Data_time_stamp_rx;
	dbcc_time_stamp_t can_0x515_ECU_FRONT_Can_Err_Counts_time_stamp_rx;
	dbcc_time_stamp_t can_0x516_ECU_REAR_Can_Err_Counts_time_stamp_rx;
	dbcc_time_stamp_t can_0x517_TCU_Can_Err_Counts_time_stamp_rx;
	dbcc_time_stamp_t can_0x7f0_LV_BMS_time_stamp_rx;
	dbcc_time_stamp_t can_0x7f1_LV_BMS_2_time_stamp_rx;
	unsigned can_0x0a0_M160_Temperature_Set_1_status : 2;
	unsigned can_0x0a0_M160_Temperature_Set_1_tx : 1;
	unsigned can_0x0a0_M160_Temperature_Set_1_rx : 1;
	unsigned can_0x0a1_M161_Temperature_Set_2_status : 2;
	unsigned can_0x0a1_M161_Temperature_Set_2_tx : 1;
	unsigned can_0x0a1_M161_Temperature_Set_2_rx : 1;
	unsigned can_0x0a2_M162_Temperature_Set_3_status : 2;
	unsigned can_0x0a2_M162_Temperature_Set_3_tx : 1;
	unsigned can_0x0a2_M162_Temperature_Set_3_rx : 1;
	unsigned can_0x0a3_M163_Analog_Input_Voltages_status : 2;
	unsigned can_0x0a3_M163_Analog_Input_Voltages_tx : 1;
	unsigned can_0x0a3_M163_Analog_Input_Voltages_rx : 1;
	unsigned can_0x0a4_M164_Digital_Input_Status_status : 2;
	unsigned can_0x0a4_M164_Digital_Input_Status_tx : 1;
	unsigned can_0x0a4_M164_Digital_Input_Status_rx : 1;
	unsigned can_0x0a5_M165_Motor_Position_Info_status : 2;
	unsigned can_0x0a5_M165_Motor_Position_Info_tx : 1;
	unsigned can_0x0a5_M165_Motor_Position_Info_rx : 1;
	unsigned can_0x0a6_M166_Current_Info_status : 2;
	unsigned can_0x0a6_M166_Current_Info_tx : 1;
	unsigned can_0x0a6_M166_Current_Info_rx : 1;
	unsigned can_0x0a7_M167_Voltage_Info_status : 2;
	unsigned can_0x0a7_M167_Voltage_Info_tx : 1;
	unsigned can_0x0a7_M167_Voltage_Info_rx : 1;
	unsigned can_0x0a8_M168_Flux_ID_IQ_Info_status : 2;
	unsigned can_0x0a8_M168_Flux_ID_IQ_Info_tx : 1;
	unsigned can_0x0a8_M168_Flux_ID_IQ_Info_rx : 1;
	unsigned can_0x0a9_M169_Internal_Voltages_status : 2;
	unsigned can_0x0a9_M169_Internal_Voltages_tx : 1;
	unsigned can_0x0a9_M169_Internal_Voltages_rx : 1;
	unsigned can_0x0aa_M170_Internal_States_status : 2;
	unsigned can_0x0aa_M170_Internal_States_tx : 1;
	unsigned can_0x0aa_M170_Internal_States_rx : 1;
	unsigned can_0x0ab_M171_Fault_Codes_status : 2;
	unsigned can_0x0ab_M171_Fault_Codes_tx : 1;
	unsigned can_0x0ab_M171_Fault_Codes_rx : 1;
	unsigned can_0x0ac_M172_Torque_And_Timer_Info_status : 2;
	unsigned can_0x0ac_M172_Torque_And_Timer_Info_tx : 1;
	unsigned can_0x0ac_M172_Torque_And_Timer_Info_rx : 1;
	unsigned can_0x0ad_M173_Modulation_And_Flux_Info_status : 2;
	unsigned can_0x0ad_M173_Modulation_And_Flux_Info_tx : 1;
	unsigned can_0x0ad_M173_Modulation_And_Flux_Info_rx : 1;
	unsigned can_0x0ae_M174_Firmware_Info_status : 2;
	unsigned can_0x0ae_M174_Firmware_Info_tx : 1;
	unsigned can_0x0ae_M174_Firmware_Info_rx : 1;
	unsigned can_0x0af_M175_Diag_Data_status : 2;
	unsigned can_0x0af_M175_Diag_Data_tx : 1;
	unsigned can_0x0af_M175_Diag_Data_rx : 1;
	unsigned can_0x0b0_M176_Fast_Info_status : 2;
	unsigned can_0x0b0_M176_Fast_Info_tx : 1;
	unsigned can_0x0b0_M176_Fast_Info_rx : 1;
	unsigned can_0x0c0_M192_Command_Message_status : 2;
	unsigned can_0x0c0_M192_Command_Message_tx : 1;
	unsigned can_0x0c0_M192_Command_Message_rx : 1;
	unsigned can_0x0c1_M193_Read_Write_Param_Command_status : 2;
	unsigned can_0x0c1_M193_Read_Write_Param_Command_tx : 1;
	unsigned can_0x0c1_M193_Read_Write_Param_Command_rx : 1;
	unsigned can_0x0c2_M194_Read_Write_Param_Response_status : 2;
	unsigned can_0x0c2_M194_Read_Write_Param_Response_tx : 1;
	unsigned can_0x0c2_M194_Read_Write_Param_Response_rx : 1;
	unsigned can_0x0c3_BMS_Fault_status : 2;
	unsigned can_0x0c3_BMS_Fault_tx : 1;
	unsigned can_0x0c3_BMS_Fault_rx : 1;
	unsigned can_0x1c0_ReadyToDrive_status : 2;
	unsigned can_0x1c0_ReadyToDrive_tx : 1;
	unsigned can_0x1c0_ReadyToDrive_rx : 1;
	unsigned can_0x1d5_M188_U2C_Message_Rxd_status : 2;
	unsigned can_0x1d5_M188_U2C_Message_Rxd_tx : 1;
	unsigned can_0x1d5_M188_U2C_Message_Rxd_rx : 1;
	unsigned can_0x1d7_M187_U2C_Command_Txd_status : 2;
	unsigned can_0x1d7_M187_U2C_Command_Txd_tx : 1;
	unsigned can_0x1d7_M187_U2C_Command_Txd_rx : 1;
	unsigned can_0x210_BrakeLight_status : 2;
	unsigned can_0x210_BrakeLight_tx : 1;
	unsigned can_0x210_BrakeLight_rx : 1;
	unsigned can_0x230_BrakePressure_status : 2;
	unsigned can_0x230_BrakePressure_tx : 1;
	unsigned can_0x230_BrakePressure_rx : 1;
	unsigned can_0x240_WheelSpeed_status : 2;
	unsigned can_0x240_WheelSpeed_tx : 1;
	unsigned can_0x240_WheelSpeed_rx : 1;
	unsigned can_0x250_SteeringPot_status : 2;
	unsigned can_0x250_SteeringPot_tx : 1;
	unsigned can_0x250_SteeringPot_rx : 1;
	unsigned can_0x260_MBRTempSens_status : 2;
	unsigned can_0x260_MBRTempSens_tx : 1;
	unsigned can_0x260_MBRTempSens_rx : 1;
	unsigned can_0x280_ECU_FRONT_BrakeTemp_status : 2;
	unsigned can_0x280_ECU_FRONT_BrakeTemp_tx : 1;
	unsigned can_0x280_ECU_FRONT_BrakeTemp_rx : 1;
	unsigned can_0x290_ECU_REAR_Brake_Temp_status : 2;
	unsigned can_0x290_ECU_REAR_Brake_Temp_tx : 1;
	unsigned can_0x290_ECU_REAR_Brake_Temp_rx : 1;
	unsigned can_0x2b0_APPS_status : 2;
	unsigned can_0x2b0_APPS_tx : 1;
	unsigned can_0x2b0_APPS_rx : 1;
	unsigned can_0x300_ECU_REAR_IMU_GYRO_status : 2;
	unsigned can_0x300_ECU_REAR_IMU_GYRO_tx : 1;
	unsigned can_0x300_ECU_REAR_IMU_GYRO_rx : 1;
	unsigned can_0x310_ECU_REAR_IMU_ACCEL_status : 2;
	unsigned can_0x310_ECU_REAR_IMU_ACCEL_tx : 1;
	unsigned can_0x310_ECU_REAR_IMU_ACCEL_rx : 1;
	unsigned can_0x4c4_BMS_Voltage_Data_status : 2;
	unsigned can_0x4c4_BMS_Voltage_Data_tx : 1;
	unsigned can_0x4c4_BMS_Voltage_Data_rx : 1;
	unsigned can_0x4c5_BMS_Temperature_Data_status : 2;
	unsigned can_0x4c5_BMS_Temperature_Data_tx : 1;
	unsigned can_0x4c5_BMS_Temperature_Data_rx : 1;
	unsigned can_0x4c6_BMS_Pack_Data_status : 2;
	unsigned can_0x4c6_BMS_Pack_Data_tx : 1;
	unsigned can_0x4c6_BMS_Pack_Data_rx : 1;
	unsigned can_0x500_CANHeartBeatLED_status : 2;
	unsigned can_0x500_CANHeartBeatLED_tx : 1;
	unsigned can_0x500_CANHeartBeatLED_rx : 1;
	unsigned can_0x514_CAN_Bus_Data_status : 2;
	unsigned can_0x514_CAN_Bus_Data_tx : 1;
	unsigned can_0x514_CAN_Bus_Data_rx : 1;
	unsigned can_0x515_ECU_FRONT_Can_Err_Counts_status : 2;
	unsigned can_0x515_ECU_FRONT_Can_Err_Counts_tx : 1;
	unsigned can_0x515_ECU_FRONT_Can_Err_Counts_rx : 1;
	unsigned can_0x516_ECU_REAR_Can_Err_Counts_status : 2;
	unsigned can_0x516_ECU_REAR_Can_Err_Counts_tx : 1;
	unsigned can_0x516_ECU_REAR_Can_Err_Counts_rx : 1;
	unsigned can_0x517_TCU_Can_Err_Counts_status : 2;
	unsigned can_0x517_TCU_Can_Err_Counts_tx : 1;
	unsigned can_0x517_TCU_Can_Err_Counts_rx : 1;
	unsigned can_0x7f0_LV_BMS_status : 2;
	unsigned can_0x7f0_LV_BMS_tx : 1;
	unsigned can_0x7f0_LV_BMS_rx : 1;
	unsigned can_0x7f1_LV_BMS_2_status : 2;
	unsigned can_0x7f1_LV_BMS_2_tx : 1;
	unsigned can_0x7f1_LV_BMS_2_rx : 1;
	can_0x0a0_M160_Temperature_Set_1_t can_0x0a0_M160_Temperature_Set_1;
	can_0x0a1_M161_Temperature_Set_2_t can_0x0a1_M161_Temperature_Set_2;
	can_0x0a2_M162_Temperature_Set_3_t can_0x0a2_M162_Temperature_Set_3;
	can_0x0a3_M163_Analog_Input_Voltages_t can_0x0a3_M163_Analog_Input_Voltages;
	can_0x0a4_M164_Digital_Input_Status_t can_0x0a4_M164_Digital_Input_Status;
	can_0x0a5_M165_Motor_Position_Info_t can_0x0a5_M165_Motor_Position_Info;
	can_0x0a6_M166_Current_Info_t can_0x0a6_M166_Current_Info;
	can_0x0a7_M167_Voltage_Info_t can_0x0a7_M167_Voltage_Info;
	can_0x0a8_M168_Flux_ID_IQ_Info_t can_0x0a8_M168_Flux_ID_IQ_Info;
	can_0x0a9_M169_Internal_Voltages_t can_0x0a9_M169_Internal_Voltages;
	can_0x0aa_M170_Internal_States_t can_0x0aa_M170_Internal_States;
	can_0x0ab_M171_Fault_Codes_t can_0x0ab_M171_Fault_Codes;
	can_0x0ac_M172_Torque_And_Timer_Info_t can_0x0ac_M172_Torque_And_Timer_Info;
	can_0x0ad_M173_Modulation_And_Flux_Info_t can_0x0ad_M173_Modulation_And_Flux_Info;
	can_0x0ae_M174_Firmware_Info_t can_0x0ae_M174_Firmware_Info;
	can_0x0af_M175_Diag_Data_t can_0x0af_M175_Diag_Data;
	can_0x0b0_M176_Fast_Info_t can_0x0b0_M176_Fast_Info;
	can_0x0c0_M192_Command_Message_t can_0x0c0_M192_Command_Message;
	can_0x0c1_M193_Read_Write_Param_Command_t can_0x0c1_M193_Read_Write_Param_Command;
	can_0x0c2_M194_Read_Write_Param_Response_t can_0x0c2_M194_Read_Write_Param_Response;
	can_0x0c3_BMS_Fault_t can_0x0c3_BMS_Fault;
	can_0x1c0_ReadyToDrive_t can_0x1c0_ReadyToDrive;
	can_0x1d5_M188_U2C_Message_Rxd_t can_0x1d5_M188_U2C_Message_Rxd;
	can_0x1d7_M187_U2C_Command_Txd_t can_0x1d7_M187_U2C_Command_Txd;
	can_0x210_BrakeLight_t can_0x210_BrakeLight;
	can_0x230_BrakePressure_t can_0x230_BrakePressure;
	can_0x240_WheelSpeed_t can_0x240_WheelSpeed;
	can_0x250_SteeringPot_t can_0x250_SteeringPot;
	can_0x260_MBRTempSens_t can_0x260_MBRTempSens;
	can_0x280_ECU_FRONT_BrakeTemp_t can_0x280_ECU_FRONT_BrakeTemp;
	can_0x290_ECU_REAR_Brake_Temp_t can_0x290_ECU_REAR_Brake_Temp;
	can_0x2b0_APPS_t can_0x2b0_APPS;
	can_0x300_ECU_REAR_IMU_GYRO_t can_0x300_ECU_REAR_IMU_GYRO;
	can_0x310_ECU_REAR_IMU_ACCEL_t can_0x310_ECU_REAR_IMU_ACCEL;
	can_0x4c4_BMS_Voltage_Data_t can_0x4c4_BMS_Voltage_Data;
	can_0x4c5_BMS_Temperature_Data_t can_0x4c5_BMS_Temperature_Data;
	can_0x4c6_BMS_Pack_Data_t can_0x4c6_BMS_Pack_Data;
	can_0x500_CANHeartBeatLED_t can_0x500_CANHeartBeatLED;
	can_0x514_CAN_Bus_Data_t can_0x514_CAN_Bus_Data;
	can_0x515_ECU_FRONT_Can_Err_Counts_t can_0x515_ECU_FRONT_Can_Err_Counts;
	can_0x516_ECU_REAR_Can_Err_Counts_t can_0x516_ECU_REAR_Can_Err_Counts;
	can_0x517_TCU_Can_Err_Counts_t can_0x517_TCU_Can_Err_Counts;
	can_0x7f0_LV_BMS_t can_0x7f0_LV_BMS;
	can_0x7f1_LV_BMS_2_t can_0x7f1_LV_BMS_2;
} POSTPACK can_obj_vehicle_h_t;

int unpack_message_vehicle(can_obj_vehicle_h_t *o, const unsigned long id, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp);
int pack_message_vehicle(can_obj_vehicle_h_t *o, const unsigned long id, uint64_t *data);
int message_dlc_vehicle(const unsigned long id);

int decode_can_0x0a0_D1_Module_A(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a0_D1_Module_A(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0a0_D2_Module_B(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a0_D2_Module_B(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0a0_D3_Module_C(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a0_D3_Module_C(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0a0_D4_Gate_Driver_Board(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a0_D4_Gate_Driver_Board(can_obj_vehicle_h_t *o, dbcc_double_t in);


int decode_can_0x0a1_D1_Control_Board_Temperature(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a1_D1_Control_Board_Temperature(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0a1_D2_RTD1_Temperature(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a1_D2_RTD1_Temperature(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0a1_D3_RTD2_Temperature(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a1_D3_RTD2_Temperature(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0a1_D4_RTD3_Temperature(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a1_D4_RTD3_Temperature(can_obj_vehicle_h_t *o, dbcc_double_t in);


int decode_can_0x0a2_D1_RTD4_Temperature(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a2_D1_RTD4_Temperature(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0a2_D2_RTD5_Temperature(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a2_D2_RTD5_Temperature(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0a2_D3_Motor_Temperature(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a2_D3_Motor_Temperature(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0a2_D4_Torque_Shudder(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a2_D4_Torque_Shudder(can_obj_vehicle_h_t *o, dbcc_double_t in);


int decode_can_0x0a3_D1_Analog_Input_1(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a3_D1_Analog_Input_1(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0a3_D2_Analog_Input_2(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a3_D2_Analog_Input_2(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0a3_D3_Analog_Input_3(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a3_D3_Analog_Input_3(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0a3_D4_Analog_Input_4(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a3_D4_Analog_Input_4(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0a3_D5_Analog_Input_5(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a3_D5_Analog_Input_5(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0a3_D6_Analog_Input_6(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a3_D6_Analog_Input_6(can_obj_vehicle_h_t *o, dbcc_double_t in);


int decode_can_0x0a4_D1_Digital_Input_1(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0a4_D1_Digital_Input_1(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0a4_D2_Digital_Input_2(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0a4_D2_Digital_Input_2(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0a4_D3_Digital_Input_3(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0a4_D3_Digital_Input_3(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0a4_D4_Digital_Input_4(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0a4_D4_Digital_Input_4(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0a4_D5_Digital_Input_5(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0a4_D5_Digital_Input_5(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0a4_D6_Digital_Input_6(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0a4_D6_Digital_Input_6(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0a4_D7_Digital_Input_7(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0a4_D7_Digital_Input_7(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0a4_D8_Digital_Input_8(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0a4_D8_Digital_Input_8(can_obj_vehicle_h_t *o, uint8_t in);


int decode_can_0x0a5_D1_Motor_Angle_Electrical(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a5_D1_Motor_Angle_Electrical(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0a5_D2_Motor_Speed(const can_obj_vehicle_h_t *o, int16_t *out);
int encode_can_0x0a5_D2_Motor_Speed(can_obj_vehicle_h_t *o, int16_t in);
int decode_can_0x0a5_D3_Electrical_Output_Frequency(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a5_D3_Electrical_Output_Frequency(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0a5_D4_Delta_Resolver_Filtered(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a5_D4_Delta_Resolver_Filtered(can_obj_vehicle_h_t *o, dbcc_double_t in);


int decode_can_0x0a6_D1_Phase_A_Current(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a6_D1_Phase_A_Current(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0a6_D2_Phase_B_Current(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a6_D2_Phase_B_Current(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0a6_D3_Phase_C_Current(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a6_D3_Phase_C_Current(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0a6_D4_DC_Bus_Current(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a6_D4_DC_Bus_Current(can_obj_vehicle_h_t *o, dbcc_double_t in);


int decode_can_0x0a7_D1_DC_Bus_Voltage(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a7_D1_DC_Bus_Voltage(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0a7_D2_Output_Voltage(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a7_D2_Output_Voltage(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0a7_D3_VAB_Vd_Voltage(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a7_D3_VAB_Vd_Voltage(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0a7_D4_VBC_Vq_Voltage(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a7_D4_VBC_Vq_Voltage(can_obj_vehicle_h_t *o, dbcc_double_t in);


int decode_can_0x0a8_D1_Flux_Command(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a8_D1_Flux_Command(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0a8_D2_Flux_Feedback(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a8_D2_Flux_Feedback(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0a8_D3_Id(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a8_D3_Id(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0a8_D4_Iq(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a8_D4_Iq(can_obj_vehicle_h_t *o, dbcc_double_t in);


int decode_can_0x0a9_D1_Reference_Voltage_1_5(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a9_D1_Reference_Voltage_1_5(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0a9_D2_Reference_Voltage_2_5(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a9_D2_Reference_Voltage_2_5(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0a9_D3_Reference_Voltage_5_0(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a9_D3_Reference_Voltage_5_0(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0a9_D4_Reference_Voltage_12_0(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0a9_D4_Reference_Voltage_12_0(can_obj_vehicle_h_t *o, dbcc_double_t in);


int decode_can_0x0aa_D1_VSM_State(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0aa_D1_VSM_State(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0aa_D1_PWM_Frequency(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0aa_D1_PWM_Frequency(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0aa_D2_Inverter_State(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0aa_D2_Inverter_State(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0aa_D5_Rolling_Counter(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0aa_D5_Rolling_Counter(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0aa_D4_Inverter_Discharge_State(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0aa_D4_Inverter_Discharge_State(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0aa_D3_Relay_1_Status(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0aa_D3_Relay_1_Status(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0aa_D3_Relay_2_Status(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0aa_D3_Relay_2_Status(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0aa_D3_Relay_3_Status(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0aa_D3_Relay_3_Status(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0aa_D3_Relay_4_Status(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0aa_D3_Relay_4_Status(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0aa_D3_Relay_5_Status(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0aa_D3_Relay_5_Status(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0aa_D3_Relay_6_Status(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0aa_D3_Relay_6_Status(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0aa_D4_Inverter_Run_Mode(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0aa_D4_Inverter_Run_Mode(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0aa_D5_Inverter_Command_Mode(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0aa_D5_Inverter_Command_Mode(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0aa_D6_Inverter_Enable_State(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0aa_D6_Inverter_Enable_State(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0aa_D6_Start_Mode_Active(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0aa_D6_Start_Mode_Active(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0aa_D6_Inverter_Enable_Lockout(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0aa_D6_Inverter_Enable_Lockout(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0aa_D7_Direction_Command(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0aa_D7_Direction_Command(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0aa_D7_BMS_Active(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0aa_D7_BMS_Active(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0aa_D7_BMS_Torque_Limiting(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0aa_D7_BMS_Torque_Limiting(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0aa_D7_Max_Speed_Limiting(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0aa_D7_Max_Speed_Limiting(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0aa_D7_Low_Speed_Limiting(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0aa_D7_Low_Speed_Limiting(can_obj_vehicle_h_t *o, uint8_t in);


int decode_can_0x0ab_D1_Post_Fault_Lo(const can_obj_vehicle_h_t *o, uint16_t *out);
int encode_can_0x0ab_D1_Post_Fault_Lo(can_obj_vehicle_h_t *o, uint16_t in);
int decode_can_0x0ab_D2_Post_Fault_Hi(const can_obj_vehicle_h_t *o, uint16_t *out);
int encode_can_0x0ab_D2_Post_Fault_Hi(can_obj_vehicle_h_t *o, uint16_t in);
int decode_can_0x0ab_D3_Run_Fault_Lo(const can_obj_vehicle_h_t *o, uint16_t *out);
int encode_can_0x0ab_D3_Run_Fault_Lo(can_obj_vehicle_h_t *o, uint16_t in);
int decode_can_0x0ab_D4_Run_Fault_Hi(const can_obj_vehicle_h_t *o, uint16_t *out);
int encode_can_0x0ab_D4_Run_Fault_Hi(can_obj_vehicle_h_t *o, uint16_t in);


int decode_can_0x0ac_D3_Power_On_Timer(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0ac_D3_Power_On_Timer(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0ac_D1_Commanded_Torque(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0ac_D1_Commanded_Torque(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0ac_D2_Torque_Feedback(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0ac_D2_Torque_Feedback(can_obj_vehicle_h_t *o, dbcc_double_t in);


int decode_can_0x0ad_D1_Modulation_Index(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0ad_D1_Modulation_Index(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0ad_D2_Flux_Weakening_Output(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0ad_D2_Flux_Weakening_Output(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0ad_D3_Id_Command(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0ad_D3_Id_Command(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0ad_D4_Iq_Command(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0ad_D4_Iq_Command(can_obj_vehicle_h_t *o, dbcc_double_t in);


int decode_can_0x0ae_D1_Project_Code_EEP_Ver(const can_obj_vehicle_h_t *o, uint16_t *out);
int encode_can_0x0ae_D1_Project_Code_EEP_Ver(can_obj_vehicle_h_t *o, uint16_t in);
int decode_can_0x0ae_D2_SW_Version(const can_obj_vehicle_h_t *o, uint16_t *out);
int encode_can_0x0ae_D2_SW_Version(can_obj_vehicle_h_t *o, uint16_t in);
int decode_can_0x0ae_D3_DateCode_MMDD(const can_obj_vehicle_h_t *o, uint16_t *out);
int encode_can_0x0ae_D3_DateCode_MMDD(can_obj_vehicle_h_t *o, uint16_t in);
int decode_can_0x0ae_D4_DateCode_YYYY(const can_obj_vehicle_h_t *o, uint16_t *out);
int encode_can_0x0ae_D4_DateCode_YYYY(can_obj_vehicle_h_t *o, uint16_t in);


int decode_can_0x0af_D3_Diag_Data_1(const can_obj_vehicle_h_t *o, int16_t *out);
int encode_can_0x0af_D3_Diag_Data_1(can_obj_vehicle_h_t *o, int16_t in);
int decode_can_0x0af_D4_Diag_Data_2(const can_obj_vehicle_h_t *o, int16_t *out);
int encode_can_0x0af_D4_Diag_Data_2(can_obj_vehicle_h_t *o, int16_t in);
int decode_can_0x0af_D5_Diag_Data_3(const can_obj_vehicle_h_t *o, int16_t *out);
int encode_can_0x0af_D5_Diag_Data_3(can_obj_vehicle_h_t *o, int16_t in);
int decode_can_0x0af_D1_Buffer_Record(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0af_D1_Buffer_Record(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0af_D2_Buffer_Segment(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0af_D2_Buffer_Segment(can_obj_vehicle_h_t *o, uint8_t in);


int decode_can_0x0b0_Fast_Torque_Command(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0b0_Fast_Torque_Command(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0b0_Fast_Torque_Feedback(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0b0_Fast_Torque_Feedback(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0b0_Fast_Motor_Speed(const can_obj_vehicle_h_t *o, int16_t *out);
int encode_can_0x0b0_Fast_Motor_Speed(can_obj_vehicle_h_t *o, int16_t in);
int decode_can_0x0b0_Fast_DC_Bus_Voltage(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0b0_Fast_DC_Bus_Voltage(can_obj_vehicle_h_t *o, dbcc_double_t in);


int decode_can_0x0c0_Torque_Command(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0c0_Torque_Command(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0c0_Speed_Command(const can_obj_vehicle_h_t *o, int16_t *out);
int encode_can_0x0c0_Speed_Command(can_obj_vehicle_h_t *o, int16_t in);
int decode_can_0x0c0_Torque_Limit_Command(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x0c0_Torque_Limit_Command(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x0c0_RollingCounter(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0c0_RollingCounter(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0c0_Direction_Command(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0c0_Direction_Command(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0c0_Inverter_Enable(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0c0_Inverter_Enable(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0c0_Inverter_Discharge(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0c0_Inverter_Discharge(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0c0_Speed_Mode_Enable(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0c0_Speed_Mode_Enable(can_obj_vehicle_h_t *o, uint8_t in);


int decode_can_0x0c1_D1_Parameter_Address_Command(const can_obj_vehicle_h_t *o, uint16_t *out);
int encode_can_0x0c1_D1_Parameter_Address_Command(can_obj_vehicle_h_t *o, uint16_t in);
int decode_can_0x0c1_D3_Data_Command(const can_obj_vehicle_h_t *o, int16_t *out);
int encode_can_0x0c1_D3_Data_Command(can_obj_vehicle_h_t *o, int16_t in);
int decode_can_0x0c1_D2_Read_Write_Command(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0c1_D2_Read_Write_Command(can_obj_vehicle_h_t *o, uint8_t in);


int decode_can_0x0c2_D1_Parameter_Address_Response(const can_obj_vehicle_h_t *o, uint16_t *out);
int encode_can_0x0c2_D1_Parameter_Address_Response(can_obj_vehicle_h_t *o, uint16_t in);
int decode_can_0x0c2_D3_Data_Response(const can_obj_vehicle_h_t *o, int16_t *out);
int encode_can_0x0c2_D3_Data_Response(can_obj_vehicle_h_t *o, int16_t in);
int decode_can_0x0c2_D2_Write_Success(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0c2_D2_Write_Success(can_obj_vehicle_h_t *o, uint8_t in);


int decode_can_0x0c3_SEG1OV(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0c3_SEG1OV(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0c3_SEG1UV(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0c3_SEG1UV(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0c3_SEG1OT(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0c3_SEG1OT(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0c3_SEG1UT(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0c3_SEG1UT(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0c3_SEG2OV(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0c3_SEG2OV(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0c3_SEG2UV(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0c3_SEG2UV(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0c3_SEG2OT(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0c3_SEG2OT(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0c3_SEG2UT(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0c3_SEG2UT(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0c3_SEG3OV(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0c3_SEG3OV(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0c3_SEG3UV(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0c3_SEG3UV(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0c3_SEG3OT(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0c3_SEG3OT(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0c3_SEG3UT(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0c3_SEG3UT(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0c3_SEG4OV(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0c3_SEG4OV(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0c3_SEG4UV(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0c3_SEG4UV(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0c3_SEG4OT(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0c3_SEG4OT(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0c3_SEG4UT(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0c3_SEG4UT(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0c3_SEG5OV(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0c3_SEG5OV(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0c3_SEG5UV(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0c3_SEG5UV(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0c3_SEG5OT(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0c3_SEG5OT(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0c3_SEG5UT(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0c3_SEG5UT(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0c3_SEG6OV(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0c3_SEG6OV(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0c3_SEG6UV(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0c3_SEG6UV(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0c3_SEG6OT(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0c3_SEG6OT(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0c3_SEG6UT(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0c3_SEG6UT(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0c3_PACKOC(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0c3_PACKOC(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0c3_IMD_Fault(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0c3_IMD_Fault(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x0c3_PEC_ERROR(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x0c3_PEC_ERROR(can_obj_vehicle_h_t *o, uint8_t in);


int decode_can_0x1c0_RTDActive(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x1c0_RTDActive(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x1c0_Buzzer(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x1c0_Buzzer(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x1c0_RegenStatus(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x1c0_RegenStatus(can_obj_vehicle_h_t *o, uint8_t in);


int decode_can_0x1d5_D3_HV_Input_Current(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x1d5_D3_HV_Input_Current(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x1d5_D6_14V_Monitor(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x1d5_D6_14V_Monitor(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x1d5_D8_14V_Current_Monitor(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x1d5_D8_14V_Current_Monitor(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x1d5_D5_DTC_Index(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x1d5_D5_DTC_Index(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x1d5_D4_DTC_Status(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x1d5_D4_DTC_Status(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x1d5_D1_HV_Input_Current_Sensor_Validity(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x1d5_D1_HV_Input_Current_Sensor_Validity(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x1d5_D2_14V_Master_Fault(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x1d5_D2_14V_Master_Fault(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x1d5_D7_14V_Conditional(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x1d5_D7_14V_Conditional(can_obj_vehicle_h_t *o, uint8_t in);


int decode_can_0x1d7_D1_ID_Byte(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x1d7_D1_ID_Byte(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x1d7_D2_Setpoint_Calc(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x1d7_D2_Setpoint_Calc(can_obj_vehicle_h_t *o, uint8_t in);


int decode_can_0x210_BrakeLightActive(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x210_BrakeLightActive(can_obj_vehicle_h_t *o, uint8_t in);


int decode_can_0x230_BrakeSensor1(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x230_BrakeSensor1(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x230_BrakeSensor2(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x230_BrakeSensor2(can_obj_vehicle_h_t *o, dbcc_double_t in);


int decode_can_0x240_SpeedFrontRight(const can_obj_vehicle_h_t *o, int16_t *out);
int encode_can_0x240_SpeedFrontRight(can_obj_vehicle_h_t *o, int16_t in);
int decode_can_0x240_SpeedFrontLeft(const can_obj_vehicle_h_t *o, int16_t *out);
int encode_can_0x240_SpeedFrontLeft(can_obj_vehicle_h_t *o, int16_t in);
int decode_can_0x240_SpeedRearRight(const can_obj_vehicle_h_t *o, int16_t *out);
int encode_can_0x240_SpeedRearRight(can_obj_vehicle_h_t *o, int16_t in);
int decode_can_0x240_SpeedRearLeft(const can_obj_vehicle_h_t *o, int16_t *out);
int encode_can_0x240_SpeedRearLeft(can_obj_vehicle_h_t *o, int16_t in);


int decode_can_0x250_SteeringPotAngle(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x250_SteeringPotAngle(can_obj_vehicle_h_t *o, dbcc_double_t in);


int decode_can_0x260_Temperature(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x260_Temperature(can_obj_vehicle_h_t *o, dbcc_double_t in);


int decode_can_0x280_ECU_FRONT_BrakeTemp_FR(const can_obj_vehicle_h_t *o, uint16_t *out);
int encode_can_0x280_ECU_FRONT_BrakeTemp_FR(can_obj_vehicle_h_t *o, uint16_t in);
int decode_can_0x280_ECU_FRONT_BrakeTemp_FL(const can_obj_vehicle_h_t *o, uint16_t *out);
int encode_can_0x280_ECU_FRONT_BrakeTemp_FL(can_obj_vehicle_h_t *o, uint16_t in);


int decode_can_0x290_ECU_REAR_Brake_Temp_RR(const can_obj_vehicle_h_t *o, uint16_t *out);
int encode_can_0x290_ECU_REAR_Brake_Temp_RR(can_obj_vehicle_h_t *o, uint16_t in);
int decode_can_0x290_ECU_REAR_Brake_Temp_RL(const can_obj_vehicle_h_t *o, uint16_t *out);
int encode_can_0x290_ECU_REAR_Brake_Temp_RL(can_obj_vehicle_h_t *o, uint16_t in);


int decode_can_0x2b0_APPS1(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x2b0_APPS1(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x2b0_APPS2(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x2b0_APPS2(can_obj_vehicle_h_t *o, dbcc_double_t in);


int decode_can_0x300_ECU_REAR_IMU_GYRO_RAW_X(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x300_ECU_REAR_IMU_GYRO_RAW_X(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x300_ECU_REAR_IMU_GYRO_RAW_Y(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x300_ECU_REAR_IMU_GYRO_RAW_Y(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x300_ECU_REAR_IMU_GYRO_RAW_Z(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x300_ECU_REAR_IMU_GYRO_RAW_Z(can_obj_vehicle_h_t *o, dbcc_double_t in);


int decode_can_0x310_ECU_REAR_IMU_ACCEL_RAW_X(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x310_ECU_REAR_IMU_ACCEL_RAW_X(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x310_ECU_REAR_IMU_ACCEL_RAW_Y(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x310_ECU_REAR_IMU_ACCEL_RAW_Y(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x310_ECU_REAR_IMU_ACCEL_RAW_Z(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x310_ECU_REAR_IMU_ACCEL_RAW_Z(can_obj_vehicle_h_t *o, dbcc_double_t in);


int decode_can_0x4c4_Max_Voltage(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x4c4_Max_Voltage(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x4c4_Min_Voltage(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x4c4_Min_Voltage(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x4c4_Avg_Voltage(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x4c4_Avg_Voltage(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x4c4_Max_Voltage_Location(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x4c4_Max_Voltage_Location(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x4c4_Min_Voltage_Location(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x4c4_Min_Voltage_Location(can_obj_vehicle_h_t *o, uint8_t in);


int decode_can_0x4c5_Max_Temperature(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x4c5_Max_Temperature(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x4c5_Min_Temperature(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x4c5_Min_Temperature(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x4c5_Avg_Temperature(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x4c5_Avg_Temperature(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x4c5_Max_Temperature_Location(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x4c5_Max_Temperature_Location(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x4c5_Min_Temperature_Location(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x4c5_Min_Temperature_Location(can_obj_vehicle_h_t *o, uint8_t in);


int decode_can_0x4c6_Pack_Voltage(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x4c6_Pack_Voltage(can_obj_vehicle_h_t *o, dbcc_double_t in);
int decode_can_0x4c6_Pack_Current(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x4c6_Pack_Current(can_obj_vehicle_h_t *o, dbcc_double_t in);


int decode_can_0x500_HeartBit(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x500_HeartBit(can_obj_vehicle_h_t *o, uint8_t in);


int decode_can_0x514_Bus_Load(const can_obj_vehicle_h_t *o, dbcc_double_t *out);
int encode_can_0x514_Bus_Load(can_obj_vehicle_h_t *o, dbcc_double_t in);


int decode_can_0x515_ECU_FRONT_TX_Hw_Err_Count(const can_obj_vehicle_h_t *o, uint16_t *out);
int encode_can_0x515_ECU_FRONT_TX_Hw_Err_Count(can_obj_vehicle_h_t *o, uint16_t in);
int decode_can_0x515_ECU_FRONT_TX_Sw_Err_Count(const can_obj_vehicle_h_t *o, uint16_t *out);
int encode_can_0x515_ECU_FRONT_TX_Sw_Err_Count(can_obj_vehicle_h_t *o, uint16_t in);
int decode_can_0x515_ECU_FRONT_RX_Hw_Err_Count(const can_obj_vehicle_h_t *o, uint16_t *out);
int encode_can_0x515_ECU_FRONT_RX_Hw_Err_Count(can_obj_vehicle_h_t *o, uint16_t in);
int decode_can_0x515_ECU_FRONT_RX_Sw_Err_Count(const can_obj_vehicle_h_t *o, uint16_t *out);
int encode_can_0x515_ECU_FRONT_RX_Sw_Err_Count(can_obj_vehicle_h_t *o, uint16_t in);


int decode_can_0x516_ECU_REAR_TX_Hw_Err_Count(const can_obj_vehicle_h_t *o, uint16_t *out);
int encode_can_0x516_ECU_REAR_TX_Hw_Err_Count(can_obj_vehicle_h_t *o, uint16_t in);
int decode_can_0x516_ECU_REAR_TX_Sw_Err_Count(const can_obj_vehicle_h_t *o, uint16_t *out);
int encode_can_0x516_ECU_REAR_TX_Sw_Err_Count(can_obj_vehicle_h_t *o, uint16_t in);
int decode_can_0x516_ECU_REAR_RX_Hw_Err_Count(const can_obj_vehicle_h_t *o, uint16_t *out);
int encode_can_0x516_ECU_REAR_RX_Hw_Err_Count(can_obj_vehicle_h_t *o, uint16_t in);
int decode_can_0x516_ECU_REAR_RX_Sw_Err_Count(const can_obj_vehicle_h_t *o, uint16_t *out);
int encode_can_0x516_ECU_REAR_RX_Sw_Err_Count(can_obj_vehicle_h_t *o, uint16_t in);


int decode_can_0x517_TCU_TX_Hw_Err_Count(const can_obj_vehicle_h_t *o, uint16_t *out);
int encode_can_0x517_TCU_TX_Hw_Err_Count(can_obj_vehicle_h_t *o, uint16_t in);
int decode_can_0x517_TCU_TX_Sw_Err_Count(const can_obj_vehicle_h_t *o, uint16_t *out);
int encode_can_0x517_TCU_TX_Sw_Err_Count(can_obj_vehicle_h_t *o, uint16_t in);
int decode_can_0x517_TCU_RX_Hw_Err_Count(const can_obj_vehicle_h_t *o, uint16_t *out);
int encode_can_0x517_TCU_RX_Hw_Err_Count(can_obj_vehicle_h_t *o, uint16_t in);
int decode_can_0x517_TCU_RX_Sw_Err_Count(const can_obj_vehicle_h_t *o, uint16_t *out);
int encode_can_0x517_TCU_RX_Sw_Err_Count(can_obj_vehicle_h_t *o, uint16_t in);


int decode_can_0x7f0_LV_BMS_Voltage(const can_obj_vehicle_h_t *o, uint16_t *out);
int encode_can_0x7f0_LV_BMS_Voltage(can_obj_vehicle_h_t *o, uint16_t in);
int decode_can_0x7f0_LV_BMS_Current(const can_obj_vehicle_h_t *o, uint16_t *out);
int encode_can_0x7f0_LV_BMS_Current(can_obj_vehicle_h_t *o, uint16_t in);
int decode_can_0x7f0_LV_BMS_Temperature(const can_obj_vehicle_h_t *o, uint16_t *out);
int encode_can_0x7f0_LV_BMS_Temperature(can_obj_vehicle_h_t *o, uint16_t in);
int decode_can_0x7f0_LV_BMS_Battery_Status(const can_obj_vehicle_h_t *o, uint16_t *out);
int encode_can_0x7f0_LV_BMS_Battery_Status(can_obj_vehicle_h_t *o, uint16_t in);


int decode_can_0x7f1_LV_BMS_Min_Cell_Voltage(const can_obj_vehicle_h_t *o, uint16_t *out);
int encode_can_0x7f1_LV_BMS_Min_Cell_Voltage(can_obj_vehicle_h_t *o, uint16_t in);
int decode_can_0x7f1_LV_BMS_Max_Cell_Voltage(const can_obj_vehicle_h_t *o, uint16_t *out);
int encode_can_0x7f1_LV_BMS_Max_Cell_Voltage(can_obj_vehicle_h_t *o, uint16_t in);
int decode_can_0x7f1_LV_BMS_Avg_Cell_Voltage(const can_obj_vehicle_h_t *o, uint16_t *out);
int encode_can_0x7f1_LV_BMS_Avg_Cell_Voltage(can_obj_vehicle_h_t *o, uint16_t in);
int decode_can_0x7f1_LV_BMS_Balancing_Status_Bitmask(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x7f1_LV_BMS_Balancing_Status_Bitmask(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x7f1_LV_BMS_Fault_Reg_Out(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x7f1_LV_BMS_Fault_Reg_Out(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x7f1_LV_BMS_Fault_Current_Protection_Latch(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x7f1_LV_BMS_Fault_Current_Protection_Latch(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x7f1_LV_BMS_Fault_Overcurrent_Charge(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x7f1_LV_BMS_Fault_Overcurrent_Charge(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x7f1_LV_BMS_Fault_Overcurrent_Discharge_2(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x7f1_LV_BMS_Fault_Overcurrent_Discharge_2(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x7f1_LV_BMS_Fault_Overcurrent_Discharge_1(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x7f1_LV_BMS_Fault_Overcurrent_Discharge_1(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x7f1_LV_BMS_Fault_Short_Circuit_Discharge(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x7f1_LV_BMS_Fault_Short_Circuit_Discharge(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x7f1_LV_BMS_Fault_Cell_Undervoltage(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x7f1_LV_BMS_Fault_Cell_Undervoltage(can_obj_vehicle_h_t *o, uint8_t in);
int decode_can_0x7f1_LV_BMS_Fault_Cell_Overvoltage(const can_obj_vehicle_h_t *o, uint8_t *out);
int encode_can_0x7f1_LV_BMS_Fault_Cell_Overvoltage(can_obj_vehicle_h_t *o, uint8_t in);


#ifdef __cplusplus
} 
#endif

#endif
